### ISSUE TITLE
Failure during handle close

### ISSUE THREAD

**Issue by quic-ekangupt** [quic/fastrpc#10]
Handle close is failing because last handle check is not proper.

**Comment by quic-cgettibo** [comment]
Handle close(**remote_handle64_close)** calls **domain_deinit** if the **is_last_handle** function returns true. The **is_last_handle** function returns the sum of domains count and non-domains count. This function is expected to return true if the handle is the last handle, but the current implementation actually does the opposite of this by returning zero even when the handle is the last one as a result of which, **domain_deinit** is not called. The modified function returns true when the sum is zero and false if it's not and with its type as bool instead of int. With these modifications, the function **is_last_handle** returns true only if it's the last handle and therefore calling **domain_deinit** on closing the handle
